### ISSUE TITLE
How can i create code of font of my language for display text in my language?

### ISSUE THREAD

**Issue by tihoangyeudau** [vvip-68/GyverStringWiFi#1]
I tried to do it by using Даня Марухленко's Bitmap Generator but its so hard and long time to do all of characters of my font? What will i need to use for doing it?

Я пытался сделать это, используя Bitmap Generator Даня Марухленко, но так сложно и долго делать все символы моего шрифта? Что мне нужно будет использовать для этого?

**Comment by vvip-68** [comment]
If your language uses english character set - is nothing to do, english letters must display correctly.
If your language uses another character set then cyrillic or english latin subset - you need draw each letter as set of bits (bits matrix).  Manually or using tools. There is no another way. Probably you also need to change procedure that get array of bits depends on code of letter.

**Comment by tihoangyeudau** [comment]
Thank you for replying. I have drawn those another characters by myself manually. But i dont know their location or numerical order  where to put them in array of font.h. i think there are rule of how to put them into that. Can you show me how to locate them?

**Comment by vvip-68** [comment]
fonts.h contains character definition array
Look at the line of character definition like that:
  {0x7f, 0x09, 0x09, 0x09, 0x01}, // F 0x46 70
Comment is character F with ASCII code 0x46 hex or 70 in decimal.
Search in google ASCII table for your language like that
https://www.ascii-code.com/
"DEC" column - decimal number of character, "HEX" - hexadecimal, "Symbol" is character symbol
Find code of symbols in your language and put your array-definition of character image into appropriate place of table defined in fonts.h

**Comment by tihoangyeudau** [comment]
Thank you i will try to do it

**Comment by tihoangyeudau** [comment]
> fonts.h contains character definition array
> Look at the line of character definition like that:
> {0x7f, 0x09, 0x09, 0x09, 0x01}, // F 0x46 70
> Comment is character F with ASCII code 0x46 hex or 70 in decimal.
> Search in google ASCII table for your language like that
> https://www.ascii-code.com/
> "DEC" column - decimal number of character, "HEX" - hexadecimal, "Symbol" is character symbol
> Find code of symbols in your language and put your array-definition of character image into appropriate place of table defined in fonts.h

Sorry, but i just saw in https://www.ascii-code.com/ where just has "DEC" column - decimal number of character, "HEX" - hexadecimal, "Symbol", but not have code same as {0x7f, 0x09, 0x09, 0x09, 0x01}. how can i create code like as {0x7f, 0x09, 0x09, 0x09, 0x01}?

**Comment by vvip-68** [comment]
{0x7f, 0x09, 0x09, 0x09, 0x01} as I understand from your message - is image of 'F' in 5x7 matrix.
```
1 1 1 1 1 1 1
0 0 0 1 0 0 1
0 0 0 1 0 0 1
0 0 0 1 0 0 1
0 0 0 0 0 0 1
```
Do you see letter F in this matrix?
First row (first element of this array) is the very left column for display pixels on matrix
Second byte 0x09 - is the second column and so further.
You said you **already created** manually image matrix for your characters.

It is your responsibility how to find position in array of charracter images fontHEX[] declared in fonts.h according to your charracter code. You must invent algorithm and use it.
For example cyrillic letters in UTF-8 are encoded with two-bytes sequencies like (in bits) 110XXXXX 10XXXXXX. It means that cyrillic symbols in UTF-8 always encодев with first byte 0xD0 оr 0xD1
All latin ASCII letters allways encode in first half of ASCII table with codes 20..127. So it in text string as byte array we meet next processing byte as 0xD0 оr 0xD1 we are sure that it is cyrillic letter. We simple skip that flag byte as senseless and process second byte of 2-bytes sequence for calculating index in font array.

Here is code in running_text.ino, lines 25-35
```
    while (text[i] != '\0') {
      if ((byte)text[i] > 191) {    // work with cyrillic. skip this and process next
        i++;
      } else {
        // draw encoded letter into led matrix 
        drawLetter(j, text[i], offset + j * (LET_WIDTH + SPACE), color);
        i++;
        j++;
      }
    }
```
If byte text[i]>191 - it is flag of next byte codes cyrillyc letter, skip it, but next iteration decode second byte inside drawLwtter() function, which calls thisByte = getFont((byte)letter, i); for getting column of pixels for put then into column of matrix drawing character.

drawLetter() retrieves columns of letter images and put all columns sequentially on screen
```
int8_t start_pos = 0, finish_pos = LET_WIDTH;
for (byte i = start_pos; i < finish_pos; i++) {
  int thisByte = getFont((byte)letter, i);
}

```
Function getFont() makes translation from second byte of encoded character to index of lement of array containing images of characters to display.
That is description how it works for latinic (english) letters and cyrillic.

```
uint8_t getFont(uint8_t font, uint8_t row) {
  font = font - '0' + 16;   // translate code from ASCII-code into character images array index
  if (font <= 90) return pgm_read_byte(&(fontHEX[font][row]));     // for english chars
  else if (font >= 112 && font <= 159) {    // lowercase cyrillic
    return pgm_read_byte(&(fontHEX[font - 17][row]));
  } else if (font >= 96 && font <= 111) {   // uppercase cyrillic
    return pgm_read_byte(&(fontHEX[font + 47][row]));
  }
}
```


I do not know which language you are using, but probably characters in your languages are encoded little bit complex.
You need to invent convertor from code of character to index of character images array.
It is your responsibility.

**Comment by tihoangyeudau** [comment]
yes i said i did it manually. but i thought you would give me your way to do it automaticly. But now if you dont have anyway to do it automaticly from https://www.ascii-code.com/ so i will do it manually. it will take a long time but it does not other way to do.

With this code: 

`uint8_t getFont(uint8_t font, uint8_t row) {
  font = font - '0' + 16;   // translate code from ASCII-code into character images array index
  if (font <= 90) return pgm_read_byte(&(fontHEX[font][row]));     // for english chars
  else if (font >= 112 && font <= 159) {    // lowercase cyrillic
    return pgm_read_byte(&(fontHEX[font - 17][row]));
  } else if (font >= 96 && font <= 111) {   // uppercase cyrillic
    return pgm_read_byte(&(fontHEX[font + 47][row]));
  }
}`

where is 90, 112, 159, 96, 111 or 47? How can i determine them?

**Comment by vvip-68** [comment]
input 'font' value is character code.
next substract code of '0' character convert code to index of '0' in fontHex, however 0..15  indexies are special symbols before '0' - we need add 16 to point of '0' char
0..90  index of latinic characters in fontHEX table
Codes 96..111 (after conver - '0'+16) corresponds to Cyrillic capital letter< howeve convert to index need substract offset 17 from code; for codes 112..159 - lowercase cyrillic need to add 47 for convert code to inex

Try to get ASCII table, pencil and piece of paper and solve some conversions from character code to index in array according this written algorithm for better understanding

It is not mine algorithm. I got it from internet with initial project and because it works, I use it without drill deep into scheme. Try to think yourself and understand it. Your task is convert character code into array index. You may write your own algorithm not based on this one.

**Comment by tihoangyeudau** [comment]
Thank you so much
