### ISSUE TITLE
С голосовым вводом и управлением по WiFi как это может работать, если смартфону нужен доступ в Internet?

### ISSUE THREAD

**Issue by AVG-N** [vvip-68/GyverStringWiFi#2]
Смартфон по WiFi подключается к ESP8266 и управление работает, но для голосового управления Googl требует подключения к Internet. 
С голосовым вводом и управлением по WiFi как это может работать, если смартфону нужен доступ в Internet?

Вы можете дать подробную инструкцию как подключить смартфон к ESP и к Internet одновременно?

**Comment by vvip-68** [comment]
Никак это без подключения к интернету работать не может.
Для работы без интернета - через bluetooth вам нужен оригинальный проект Алекса Гайвера - https://alexgyver.ru/gyverstring/

**Comment by AVG-N** [comment]
Я понимаю что без подключения к интернету работать не может.
Я и спросил инструкцию как одновременно подключится со смартфона к ESP и к Internet?
У меня если смартфон подключается к ESP по WiFi , то отключается мобильный 3G.
