### ISSUE TITLE
Здравствуйте не смог найти куда написать в личные сообщения

### ISSUE THREAD

**Issue by strigun14** [vvip-68/GyverStringWiFi#3]
подскажите мне начинающему, собираю ваши проекты. очень нравиться работать с NodeMcu . на вайфай. есть два вопроса
Как управлять голосом если голос распознается когда есть интернет в телефоне, а когда подключен к контроллеру , и к программе интернета нет.
И как убрать дрожание, поддергивание текста ,если уменьшить скорость бегущей строки строка идет рывками

**Comment by vvip-68** [comment]
Распознавание голоса - функция Андроид, предоставляемая Гуглем. Собранный образец голоса телефон отправляет на сервера гугля, там обрабатываются, затем результат возвращается обратно телефону. Вывод - если нет интернета - распознавание голоса работать не будет.

Рывки - не замечал. Будет свободное время - вернусь к проекту, посмотрю. Если это исправимо - попытаюсь исправить. Но с ходу я не вижу причины...

**Comment by vvip-68** [comment]
Дошли руки посмотреть эту старую прошивку. Никаких проблем ("дрожание") с текстом не обнаружил. Каждый такт текст смещается на одну колонку. Хоть быстро, хоть медленно - дрожания не наблюдаю.

**Comment by strigun14** [comment]
27.03.2021, 10:15, "vvip-68" ***@***.***>:
Дошли руки посмотреть эту старую прошивку. Никаких проблем ("дрожание") с текстом не обнаружил. Каждый такт текст смещается на одну колонку. Хоть быстро, хоть медленно - дрожания не наблюдаю.

**Comment by vvip-68** [comment]
А как плавно? Покажите где вы видели плавное смещение? Светодиод - штука дискретная - либо горит, либо нет. Между колонками диодов светиться нечему. Делайте матрицу с очень плотным размещением диодов тогда видимость плавного движения будет выраженнее.
Видео - тут: https://drive.google.com/file/d/1aLEGLjGIilPBdZrnAW92iJSZvAt6lg-9/view?usp=sharing

**Comment by strigun14** [comment]
27.03.2021, 11:39, "vvip-68" ***@***.***>:
А как плавно? Покажите где вы видели плавное смещение? Светодиод - штука дискретная - либо горит, либо нет. Мужду колонками диодов светиться нечему. Делайте матрицу с очень плотным размещением диодов тогда видимость плавного движения будет выраженнее.
Видео - тут: https://drive.google.com/file/d/1aLEGLjGIilPBdZrnAW92iJSZvAt6lg-9/view?usp=sharing

**Comment by vvip-68** [comment]
Чем больше плотность диодов (меньше расстояние между точками) - тем меньше скорость смещения, при которой движение выглядит плавным. Таково свойство глаза. Поставьте на матрице max7219 маленькую скорость как только возможно - тоже увидите, что сдвиг идет по колонкам. Между колонок диодов нет - светиться нечему.

Совсем теоретически - можно с целочисленной арифметики позиции X,Y перейти на арифметику с плавающей точкой. Тогда, например, по иксу координата будет типа X=10.5 - будет означать, что обе колонки 10 и 11 светятся с примерно одинаковой яркостью. При увеличении смещения (координата 10.7 - 10-я колонка начинает светиться тусклее, 11-я ярче.
Но текст будет "замыленным", хотя? вероятно, и будет более плавное смещение визуально.

Пробуйте - может вам так больше понравится.

**Comment by strigun14** [comment]
27.03.2021, 12:01, "vvip-68" ***@***.***>:
Чем больше плотность диодов (меньше расстояние между точками) - тем меньше скорость смещения, при которой движение выглядит плавным. Таково свойство глаза. Поставьте на матрице max7219 маленькую скорость как только возможно - тоже увидите, что сдвиг идет по колонкам. Между колонок диодов нет - светиться нечему.
Совсем теоретически - можно с целочисленной арифметики позиции X,Y перейти на арифметику с плавающей точкой. Тогда, например, по иксу координата будет типа X=10.5 - будет означать, что обе колонки 10 и 11 светятся с примерно одинаковой яркостью. При увеличении смещения (координата 10.7 - 10-я колонка начинает светиться тусклее, 11-я ярче.
Но текст будет "замыленным", хотя? вероятно, и будет более плавное смещение визуально.
Пробуйте - может вам так больше понравится.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

VID_20210315_003825.mp4 (27996649)

**Comment by strigun14** [comment]
27.03.2021, 12:01, "vvip-68" ***@***.***>:
Чем больше плотность диодов (меньше расстояние между точками) - тем меньше скорость смещения, при которой движение выглядит плавным. Таково свойство глаза. Поставьте на матрице max7219 маленькую скорость как только возможно - тоже увидите, что сдвиг идет по колонкам. Между колонок диодов нет - светиться нечему.
Совсем теоретически - можно с целочисленной арифметики позиции X,Y перейти на арифметику с плавающей точкой. Тогда, например, по иксу координата будет типа X=10.5 - будет означать, что обе колонки 10 и 11 светятся с примерно одинаковой яркостью. При увеличении смещения (координата 10.7 - 10-я колонка начинает светиться тусклее, 11-я ярче.
Но текст будет "замыленным", хотя? вероятно, и будет более плавное смещение визуально.
Пробуйте - может вам так больше понравится.

**Comment by strigun14** [comment]
Остался один вопрос.если подключен к программе ,то вайфай в телефоне занят и интнрнета нет.значит и слова диктовать я не смогу.По этому наверное Алекс Гувер и делал с управлением по блютуз.27.03.2021, 12:34, ***@***.***" ***@***.***>:27.03.2021, 12:01, "vvip-68" ***@***.***>:
Чем больше плотность диодов (меньше расстояние между точками) - тем меньше скорость смещения, при которой движение выглядит плавным. Таково свойство глаза. Поставьте на матрице max7219 маленькую скорость как только возможно - тоже увидите, что сдвиг идет по колонкам. Между колонок диодов нет - светиться нечему.
Совсем теоретически - можно с целочисленной арифметики позиции X,Y перейти на арифметику с плавающей точкой. Тогда, например, по иксу координата будет типа X=10.5 - будет означать, что обе колонки 10 и 11 светятся с примерно одинаковой яркостью. При увеличении смещения (координата 10.7 - 10-я колонка начинает светиться тусклее, 11-я ярче.
Но текст будет "замыленным", хотя? вероятно, и будет более плавное смещение визуально.
Пробуйте - может вам так больше понравится.

**Comment by vvip-68** [comment]
Скорее всего да, поэтому. Но и на момент написания его бегущей строки - он еще ничего не делал на WiFi и ESP8266 - он после это освоил. Так а в чем проблема то - есть же у него работающий проект с Bluetooth - берите его.
У меня конкретно этот проект - "чисто учебный". Я на нем разбирался как приложение в Thunkable писать, плюс немного экспериментов с WiFi и ESP8266. Практической, воплощенной в железе модели я не делал - потыкался на макетке и разобрал.

**Comment by strigun14** [comment]
да и на этом большое спасибо27.03.2021, 18:04, "vvip-68" ***@***.***>:
Скорее всего да, поэтому. Но и на момент написания его бегущей строки - он еще ничего не делал на WiFi и ESP8266 - он после это освоил. Так а в чем проблема то - есть же у него работающий проект с Bluetooth - берите его.
У меня конкретно этот проект - "чисто учебный". Я на нем разбирался как приложение в Thunkable писать, плюс немного экспериментов с WiFi и ESP8266. Практической, воплощенной в железе модели я не делал - потыкался на макетке и разобрал.

**Comment by strigun14** [comment]
ПОДСКАЖИТЕ пожалуйста ,я сделал матрицу на 13 строк, ставлю в скетче 13 по вертикали ,а буквы все ровно бегут в 7 строках, во вкладке "работа с бегущим текстом" тоже изменял высоту буквы, все ровно. , выше ниже сдвигается , но больше 8 строк не задействованы..Помогите пожалуйста, где изменить чтоб всю матрицу задействовать 27.03.2021, 18:04, "vvip-68" ***@***.***>: Скорее всего да, поэтому. Но и на момент написания его бегущей строки - он еще ничего не делал на WiFi и ESP8266 - он после это освоил. Так а в чем проблема то - есть же у него работающий проект с Bluetooth - берите его.У меня конкретно этот проект - "чисто учебный". Я на нем разбирался как приложение в Thunkable писать, плюс немного экспериментов с WiFi и ESP8266. Практической, воплощенной в железе модели я не делал - потыкался на макетке и разобрал.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by vvip-68** [comment]
Изображение буквы (шрифт 5x8) определено в файле Fonts.h
Если вам нужны буквы другого размера - вам нужно переопределить все "изображения" для каждой буквы в этом массиве под нужный размер шрифта, затем изменить процедуры drawLetter(), getFont() и связанные в файле runningText.ino так, чтобы они уже работали с новым размером знакоместа, с новым размером букв.

Сейчас один из самых упорных пользователей занимается рисованием букв под размер букв 10x16 - если он поделится ими - я выложу шрифт такого размера. Но для вашей матрицы на 13 он все равно не подойдет - буквы будут слишком велики. Так что вам всё равно придется рисовать все буквы нужного размера самостоятельно.

**Comment by vvip-68** [comment]
https://github.com/vvip-68/GyverPanelWiFi/wiki/%D0%91%D0%BE%D0%BB%D1%8C%D1%88%D0%B8%D0%B5-%D0%B1%D1%83%D0%BA%D0%B2%D1%8B-%D0%B2-%D0%B1%D0%B5%D0%B3%D1%83%D1%89%D0%B5%D0%B9-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B5

**Comment by strigun14** [comment]
я сам не сумею этого сделать. Значит получается нет смысла  собирать матрицу больше 8 строк?а какую матрицу нужно собрать ,чтоб его большие буквы у меня отображались хорошо? я соберу, может есть его скетч? с описанием. или куда ему написать? спросить. Собрал большую матрицу  на 780 светодиодов. и хотел еще больше. рисунки идут красиво, по всей матрице прошивал GyverPanelWiFi-master по всей матрице. а текст хоть стреляй 7-8 строк.   08.04.2021, 05:32, "vvip-68" ***@***.***>:
Изображение буквы (шрифт 5x8) определено в файле Fonts.h
Если вам нужны буквы другого размера - вам нужно переопределить все "изображения" для каждой буквы в этом массиве под нужный размер шрифта, затем изменить процедуры drawLetter(), getFont() и связанные в файле runningText.ino так, чтобы они уже работали с новым размером знакоместа, с новым размером букв.
Сейчас один из самых упорных пользователей занимается рисованием букв под размер букв 10x16 - если он поделится ими - я выложу шрифт такого размера. Но для вашей матрицы на 13 он все равно не подойдет - буквы будут слишком велики. Так что вам всё равно придется рисовать все буквы нужного размера самостоятельно.

**Comment by vvip-68** [comment]
ВКонтакте - Влад Мамчур - https://vk.com/mvabisnes

**Comment by strigun14** [comment]
Обьявите там приз что ли какой, я готов заплатить за работающий Скетч, чтоб текст шел в 12 строк 08.04.2021, 10:13, "vvip-68" ***@***.***>:
https://github.com/vvip-68/GyverPanelWiFi/wiki/%D0%91%D0%BE%D0%BB%D1%8C%D1%88%D0%B8%D0%B5-%D0%B1%D1%83%D0%BA%D0%B2%D1%8B-%D0%B2-%D0%B1%D0%B5%D0%B3%D1%83%D1%89%D0%B5%D0%B9-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B5

**Comment by vvip-68** [comment]
Есть у Гайвера на сайте "ищу разработчика" - спросите там.
Договоритесь с Владом - если согласится - заплатите ему сколько договоритесь, он сделает
Подождите месяц-другой - если у меня дойдут руки я напишу утилитку, облегчающую рисование символов шрифта - сами нарисуете себе свой шрифт, какой нужно.

**Comment by strigun14** [comment]
Спасибо было бы классно, в любом случае делайте, вам тысячи людей будут благодарны .те кто ,как я  не умеют сильно п прошивку лезть. напишите если что, или если появится человек который сможет мне помочь( за вознаграждение ).08.04.2021, 10:20, "vvip-68" ***@***.***>:
Есть у Гайвера на сайте "ищу разработчика" - спросите там.
Договоритесь с Владом - если согласится - заплатите ему сколько договоритесь, он сделает
Подождите месяц-другой - если у меня дойдут руки я напишу утилитку, облегчающую рисование символов шрифта - сами нарисуете себе свой шрифт, какой нужно.

**Comment by vvip-68** [comment]
https://github.com/vvip-68/GyverPanelWiFi/wiki/%D0%91%D0%BE%D0%BB%D1%8C%D1%88%D0%B8%D0%B5-%D0%B1%D1%83%D0%BA%D0%B2%D1%8B-%D0%B2-%D0%B1%D0%B5%D0%B3%D1%83%D1%89%D0%B5%D0%B9-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B5

Дописал в самом конце еще чуток

**Comment by strigun14** [comment]
Да супер, вроде скачал прогу эту .буду пробовать , огромное спасибо08.04.2021, 21:57, "vvip-68" ***@***.***>:
https://github.com/vvip-68/GyverPanelWiFi/wiki/%D0%91%D0%BE%D0%BB%D1%8C%D1%88%D0%B8%D0%B5-%D0%B1%D1%83%D0%BA%D0%B2%D1%8B-%D0%B2-%D0%B1%D0%B5%D0%B3%D1%83%D1%89%D0%B5%D0%B9-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B5
Дописал в самом конце еще чуток

**Comment by vvip-68** [comment]
Просто к слову, на всякий случай - в проектах GyverPanelWiFi и GyverStringWiFi в самых последних версиях есть возможность в настройках скетча выбрать один из трех размеров шрифтов - 5x8 (5x10), 8x13 (8x17) и 10x16 (10x20)
Размер в скобках - высота матрицы, которая нужна для шрифта, если используются символы с диакритикой типа 
Ё Ї Č Ž Ė Ū Д Ц Щ Ą ą Ę ę ų Į į Ų

**Comment by strigun14** [comment]
иные значения не пойдут?  если я матрицу сделал 13 строк. текст пишу 7 на 12.13.04.2021, 20:58, "vvip-68" ***@***.***>:
Просто к слову, на всякий случай - в проектах GyverPanelWiFi и GyverStringWiFi в самых последних версиях есть возможность в настройках скетча выбрать один из трех размеров шрифтов - 5x8 (5x10), 8x13 (8x17) и 10x16 (10x20)
Размер в скобках - высота матрицы, которая нужна для шрифта, если используются символы с диакритикой типа
Ё Ї Č Ž Ė Ū Д Ц Щ Ą ą Ę ę ų Į į Ų

**Comment by vvip-68** [comment]
Для иных размеров шрифтов нужно переписывать шрифты. "Как" и утилиту для формирования изображения символа я давал выше.

**Comment by strigun14** [comment]
что то я запутался.. т е мне нужно писать текст 8на 13? значит я не могу делать текст 7на 12? если я сделаю каждую букву 7 на 12 и вставлю в runningText. они не пойдут?14.04.2021, 17:48, "vvip-68" ***@***.***>:
Для иных размеров шрифтов нужно переписывать шрифты. "Как" и утилиту для формирования изображения символа я давал выше.

**Comment by vvip-68** [comment]
Шрифты (буквы) указанных размеров уже есть в скетче. в файле fonts.h
Если нужны шрифты (буквы) другого рfзмера - их нужно а) нарисовать. б) поместить массив нарисованных символов в файл fonts.h в) в скетче указать размеры букв вашего шрифта. Больше ничего исправлять не нужно - после компиляции скетч всё подхватит и будет отображать нарисованный вами шрифт в бегущей строке

**Comment by strigun14** [comment]
в файле fonts.h только шрифт 5 на 814.04.2021, 18:17, "vvip-68" ***@***.***>:
Шрифты (буквы) указанных размеров уже есть в скетче. в файле fonts.h
Если нужны шрифты (буквы) другого рfзмера - их нужно а) нарисовать. б) поместить массив нарисованных символов в файл fonts.h в) в скетче указать размеры букв вашего шрифта. Больше ничего исправлять не нужно - после компиляции скетч всё подхватит и будет отображать нарисованный вами шрифт в бегущей строке

**Comment by vvip-68** [comment]
Попробуйте скачать с гитхаба свежую версию скетча

**Comment by strigun14** [comment]
точно блин. есть в последней  версии. Наконец то. Я уже голову сломал с этим шрифтом.БОльшушее большущее вам спасибо.Низкий паклон. Вы просто волшебник.14.04.2021, 18:35, "vvip-68" ***@***.***>:
Попробуйте скачать с гитхаба свежую версию скетча
