### ISSUE TITLE
Исходник приложения

### ISSUE THREAD

**Issue by neverbrokeagain19** [vvip-68/GyverStringWiFi#4]
Здраствуйте, я не нашел у Гавера в проекте Бегущая строка управление по блютуз картинки с кодом приложения, можете добавить в свой проект, пожалуйста

**Comment by vvip-68** [comment]
Что такое картинка с кодом приложения? Для чего на нужна? Мой проект блютуз не поддерживает.

**Comment by neverbrokeagain19** [comment]
я не могу открыть сам код приложения, через .aia в Thunkable, и посмотреть его, поэтому нужно хотя бы на фотке, скрине в самом приложении

**Comment by vvip-68** [comment]
К чему вам эти сложности и возня с картинками?
Откройте aia-файл в AppInventor. Он прекрасно открывается (правда с предупреждением), но проект создает, все блоки вроде бы на месте, даже apk собирается.

**Comment by neverbrokeagain19** [comment]
Да, я тоже попробовал в App Inventor, но выскакивает предупреждение и после него ничего не делается, думаете если там открыть, переделать и загрузить на Андроид будет работать?

**Comment by vvip-68** [comment]
Я проверял - оно в AppInventor загружается и собирается. А будет ли работать - ХЗ - я не пробовал.
Но не вижу причин, чтобы не работало. В самом крайнем случае мог отвалиться тот код,  на элементы которого выскакивает предупреждение. А это switch (toggler) - я там вижу только два тогглера на экране. И блоки кода на них есть.
Если что-то с ними и отвалится - ну, поправишь...

**Comment by neverbrokeagain19** [comment]
когда я его добавляю и хочу открыть выбивает ошибку со спинером(Spiner) и после этого я нажимаю да на предупреждение и все дальше не фурычит

**Comment by vvip-68** [comment]
Вот файл, считанный в AppInventor из aia- от Thunkable, затем пересохраненный из AppInventor.
Попробуйте его.

[GyverStringWiFi.zip](https://github.com/vvip-68/GyverStringWiFi/files/6489595/GyverStringWiFi.zip)

**Comment by neverbrokeagain19** [comment]
Этот файл открывается, но мне нужен файл чтобы через блютуз управлять можно, ты же усовершенствовал проект его, но я приложение блютуз нашел при скачивании, и когда я файл .aia вставляю в AppInventor то пишет что есть Thinkable Switch, которого нет в AppInventor. Поэтому не мог ли ты сделать чтобы я смог открыть в AppInventor?

**Comment by vvip-68** [comment]
У меня нет исходников с блютуз. Это к Гайверу.
Проект по смыслу, функциям  и визуально похож, но делался на основе совершенно другого проекта в котором блютуз изначально не было.

**Comment by neverbrokeagain19** [comment]
а можно твой проект переделать под блютуз? И сложно это будет?

**Comment by vvip-68** [comment]
А смысл, если есть готовый проект под блютуз с точно таким же функционалом? И кто этим будет заниматься? Впрочем - если не жалко времени - пробуйте, переделывайте.

**Comment by neverbrokeagain19** [comment]
вся суть в том что я уже сделал проект Гавера и хочу увеличить функционал, добавив новые режимы, которых нет у Гавера, но я столкнулся с проблемой невозможности открыть проект в AppInventor, и увидел проект у вас, он похожий и открывается в AppInventor, поэтому спрашиваю про все это

**Comment by vvip-68** [comment]
Он только внешне похожий. Внутренний код прошивки там - процентов 10% может совпадений только. А весь протокол обмена сообщениями между прошивкой и программой не телефоне - вообще другой.

А от меня то вы что хотите? Пишите автору проекта, договаривайтесь с ним. может он уберет несовместимые компоненты/заменит из другими, совместимыми и перенесет приложение в AppInventor.

Пишите вообще своё приложение в AppInventor, используя систему команд и протокол прошивки автора.
Спрашивайте у него описание протокола.

**Comment by vvip-68** [comment]
Вот я взял исходник с сайта Гайвера, вручную поменял ThunkableSwitch на который ругается - на CheckBox
Проект с предупреждениями загружается в AppInventor, но появляется в списке проектов и открывается как в дизайнере, так и в редакторе блоков кода.

[GyverString.zip](https://github.com/vvip-68/GyverStringWiFi/files/6503136/GyverString.zip)

Мог бы и сам поправить...

**Comment by neverbrokeagain19** [comment]
Спасибо огромное, работает в AppInventor, я не мог зайти в Thunkable потому что туда нельзя зарегистрироватся и поменять этот блок чтобы запустилось(

**Comment by vvip-68** [comment]
Более того скажу, даже те кто был зарегистрирован в Thunkable Classic  тоже не могут туда зайти - всё закрыли...
